variable "owner" {}
variable "cidr_block" {}
variable "public_subnet_cidrs" {}
variable "private_subnet_cidrs" {}
variable "name" {}
variable "azs" {}
variable "image_name" {}
variable "key_name" {}
variable "env" {}